export const theme = {
  bgcolor: "#ffffff",
  textcolor: "#5b6170",
  auxbackcolor: "#f1f1f1",
  primarycolor: "#1ea5db",
  secondarycolor: "#E63828",
  primarytextcolor: "#ffffff",
  bordercolor: "#ccc",
  linescolor: "#eee",
  defaultbuttonbackcolor: "#B8BBC1",
  defaultbuttontextcolor: "#434A5B",
  primarybuttonbackcolor: "#B8BBC1",
  primarybuttontextcolor: "#434A5B",
  dangerbuttonbackcolor: "#B8BBC1",
  dangerbuttontextcolor: "#434A5B",
  stepheadingtextcolor: "#ffffff",
  stepheadingbackcolor: "#026465", // "#1ea5db",
  steptextcolor: "#5b6170",
  stepbackgroundcolor: "#ffffff",
};
